from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from .cleaner import clean_content
from .context import AuditContext
from .error_bank import find_error_bank_entries

SECTION_TITLES = (
    "§1 Active intent",
    "§2 Next concrete action",
    "§3 Directives (this session)",
    "§4 Task tree",
    "§5 Current work",
    "§6 Files and code sections",
    "§7 Discovered knowledge",
    "§8 Errors and fixes",
    "§9 Live resources",
    "§10 Design decisions and discussion outcomes",
    "§11 Open notes",
)

DEFAULT_CAPS = {
    "checkpoint": 11_000,
    "project_memory": 10_000,
    "notes": 6_000,
    "engram_recall": 6_000,
    "recent_user": 16_000,
    "fresh_tail": 9_000,
}

NOISE_MARKERS = (
    "Historical Task Snapshot",
    "Completed Actions",
    "CONTEXT COMPACTION",
    "CONTROLLED CONTEXT REBUILD",
    "[Your active task list was preserved across context compression]",
    "CONTEXT COMPACTION — REFERENCE ONLY",
)


@dataclass(frozen=True)
class ContextDoc:
    path: Path
    scope: str
    body: str


def fetch_session_messages(conn, session_id: str, *, active_only: bool = False):
    """Read one Hermes session transcript in chronological order."""
    active_clause = ""
    if active_only and _has_column(conn, "messages", "active"):
        active_clause = " AND COALESCE(m.active, 1)=1"
    cursor = conn.execute(
        f"""
        SELECT m.session_id, m.role, m.content, m.timestamp, s.title
        FROM messages m
        JOIN sessions s ON m.session_id = s.id
        WHERE m.session_id = ?{active_clause}
        ORDER BY m.timestamp ASC, m.rowid ASC
        """,
        (session_id,),
    )
    return [row for row in cursor.fetchall() if row["content"]]


def write_checkpoint(
    context: AuditContext,
    session_id: str,
    messages,
    *,
    dry_run: bool = False,
    log=print,
) -> Path:
    """Write MiMo-style session checkpoint.md from already-fetched messages."""
    path = session_checkpoint_path(context, session_id)
    content = build_checkpoint(session_id, messages)
    if dry_run:
        log(f"DRY-RUN: would write checkpoint {path}")
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    log(f"Checkpoint written: {path}")
    return path


def build_checkpoint(session_id: str, messages) -> str:
    clean_rows = _clean_rows(messages)
    users = [row for row in clean_rows if row.get("role") == "user"]
    assistants = [row for row in clean_rows if row.get("role") == "assistant"]
    latest_user = _content(users[-1]) if users else "(no user intent found)"
    latest_assistant = (
        _content(assistants[-1]) if assistants else "(no assistant work yet)"
    )
    errors = find_error_bank_entries(clean_rows)
    literals = _extract_literals("\n".join(_content(row) for row in clean_rows))
    sections = {
        SECTION_TITLES[0]: latest_user,
        SECTION_TITLES[1]: _first_line(latest_assistant),
        SECTION_TITLES[2]: _collect_directives(users),
        SECTION_TITLES[
            3
        ]: "- [ ] Continue from active intent\n- [ ] Verify with tests/gates",
        SECTION_TITLES[4]: _tail(clean_rows, limit=4),
        SECTION_TITLES[5]: "\n".join(f"- `{item}`" for item in literals)
        or "(none detected)",
        SECTION_TITLES[6]: _collect_learning(assistants),
        SECTION_TITLES[7]: _format_errors(errors),
        SECTION_TITLES[8]: _collect_resources(clean_rows),
        SECTION_TITLES[9]: _collect_decisions(clean_rows),
        SECTION_TITLES[10]: "(none)",
    }
    lines = [
        f"# Session checkpoint: {session_id}",
        "",
        "Generated by self-ershov-memory controlled rebuild sidecar.",
        "",
    ]
    for title in SECTION_TITLES:
        lines.extend([f"## {title}", sections[title].strip() or "(empty)", ""])
    return "\n".join(lines)


def rebuild_packet(
    context: AuditContext,
    session_id: str,
    messages,
    *,
    budget: int = 48_000,
) -> str:
    """Build deterministic controlled-context-rebuild packet with capped sections."""
    caps = _scaled_caps(budget)
    checkpoint = _read_if_exists(session_checkpoint_path(context, session_id))
    notes = _read_if_exists(session_notes_path(context, session_id))
    project_memory = _read_joined(
        [context.context_dir / "projects", context.context_dir / "global"]
    )
    clean_rows = _clean_rows(messages)
    recent_user = _recent_user(clean_rows, cap=caps["recent_user"])
    fresh_tail = _tail(clean_rows, limit=6)
    body = {
        "Active intent": _extract_section(checkpoint, SECTION_TITLES[0]) or recent_user,
        "Next concrete action": _extract_section(checkpoint, SECTION_TITLES[1])
        or "Continue current task.",
        "Task ledger": _extract_section(checkpoint, SECTION_TITLES[3]),
        "Session checkpoint": _cap(checkpoint, caps["checkpoint"]),
        "Recent user input (verbatim)": recent_user,
        "Project memory": _cap(project_memory, caps["project_memory"]),
        "Engram recall": "(external Engram recall is injected by Hermes tools, not this sidecar)",
        "Error Bank hints": _extract_section(checkpoint, SECTION_TITLES[7]),
        "Fresh tail": _cap(fresh_tail, caps["fresh_tail"]),
        "Notes": _cap(notes, caps["notes"]),
    }
    lines = ["[CONTROLLED CONTEXT REBUILD]"]
    for title, text in body.items():
        lines.extend([f"## {title}", text.strip() or "(empty)", ""])
    lines.append("[/CONTROLLED CONTEXT REBUILD]")
    return "\n".join(lines)


def index_context(context: AuditContext) -> int:
    """Rebuild local SQLite FTS5 index for context markdown files."""
    context.context_dir.mkdir(parents=True, exist_ok=True)
    docs = list(_iter_context_docs(context.context_dir))
    conn = sqlite3.connect(context_fts_db(context))
    try:
        conn.execute("DROP TABLE IF EXISTS context_docs")
        conn.execute("DROP TABLE IF EXISTS context_fts")
        conn.execute(
            "CREATE TABLE context_docs(path TEXT PRIMARY KEY, scope TEXT, body TEXT)"
        )
        conn.execute("CREATE VIRTUAL TABLE context_fts USING fts5(path, scope, body)")
        for doc in docs:
            rel = str(doc.path.relative_to(context.context_dir))
            conn.execute(
                "INSERT INTO context_docs VALUES (?, ?, ?)", (rel, doc.scope, doc.body)
            )
            conn.execute(
                "INSERT INTO context_fts(path, scope, body) VALUES (?, ?, ?)",
                (rel, doc.scope, doc.body),
            )
        conn.commit()
        return len(docs)
    finally:
        conn.close()


def search_context(
    context: AuditContext, query: str, *, limit: int = 5
) -> list[ContextDoc]:
    if not query.strip() or not context_fts_db(context).exists():
        return []
    conn = sqlite3.connect(context_fts_db(context))
    try:
        rows = conn.execute(
            """
            SELECT path, scope, body
            FROM context_fts
            WHERE context_fts MATCH ?
            ORDER BY bm25(context_fts)
            LIMIT ?
            """,
            (_fts_query(query), limit),
        ).fetchall()
    finally:
        conn.close()
    return [ContextDoc(context.context_dir / row[0], row[1], row[2]) for row in rows]


def session_checkpoint_path(context: AuditContext, session_id: str) -> Path:
    return (
        context.context_dir / "sessions" / _safe_component(session_id) / "checkpoint.md"
    )


def session_notes_path(context: AuditContext, session_id: str) -> Path:
    return context.context_dir / "sessions" / _safe_component(session_id) / "notes.md"


def context_fts_db(context: AuditContext) -> Path:
    return context.context_dir / "context_fts.db"


def _has_column(conn, table: str, column: str) -> bool:
    return any(row[1] == column for row in conn.execute(f"PRAGMA table_info({table})"))


def _message_dict(message) -> dict:
    if isinstance(message, dict):
        return dict(message)
    try:
        return {key: message[key] for key in message.keys()}
    except AttributeError:
        return {}


def _clean_rows(messages) -> list[dict]:
    rows = [_message_dict(message) for message in messages]
    return [
        row for row in rows if _content(row) and not _is_summary_noise(_content(row))
    ]


def _content(row: dict) -> str:
    return clean_content(row.get("content", ""))


def _is_summary_noise(text: str) -> bool:
    return any(marker in text for marker in NOISE_MARKERS) or text.count("[tool:") >= 3


def _first_line(text: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line:
            return line[:240]
    return "(empty)"


def _collect_directives(users: list[dict]) -> str:
    lines = []
    for row in users:
        text = _content(row)
        if re.search(
            r"\b(always|never|must)\b|(?:всегда|никогда|нужно|надо|обязан|запомни)",
            text,
            re.IGNORECASE,
        ):
            lines.append(f"- {text[:240]}")
    return "\n".join(lines) or "(none)"


def _tail(rows: list[dict], *, limit: int) -> str:
    tail = rows[-limit:]
    return "\n".join(f"- {row.get('role', '?')}: {_content(row)[:500]}" for row in tail)


def _extract_literals(text: str) -> list[str]:
    patterns = [r"/[\w./@+-]+", r"\b\w+\.py\b", r"\b\w+\.md\b", r"\b\d{2,5}\b"]
    found: list[str] = []
    for pattern in patterns:
        found.extend(re.findall(pattern, text))
    deduped = []
    for item in found:
        if item not in deduped:
            deduped.append(item)
    return deduped[:20]


def _collect_learning(assistants: list[dict]) -> str:
    lines = []
    for row in assistants:
        text = _content(row)
        if re.search(
            r"learned|discovered|root cause|вывод|наш[её]л|причин", text, re.IGNORECASE
        ):
            lines.append(f"- {text[:300]}")
    return "\n".join(lines) or "(none)"


def _format_errors(entries) -> str:
    return (
        "\n".join(f"- {entry.topic_key}: {entry.title}" for entry in entries)
        or "(none)"
    )


def _collect_resources(rows: list[dict]) -> str:
    text = "\n".join(_content(row) for row in rows)
    urls = re.findall(r"https?://\S+", text)
    return "\n".join(f"- {url.rstrip('.,)')}" for url in urls[:20]) or "(none)"


def _collect_decisions(rows: list[dict]) -> str:
    lines = []
    for row in rows:
        text = _content(row)
        if re.search(r"решени|decision|бер[её]м|выбран|итог", text, re.IGNORECASE):
            lines.append(f"- {text[:300]}")
    return "\n".join(lines) or "(none)"


def _scaled_caps(budget: int) -> dict[str, int]:
    factor = max(0.1, min(1.0, budget / 48_000))
    return {key: max(500, int(value * factor)) for key, value in DEFAULT_CAPS.items()}


def _read_if_exists(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _read_joined(dirs: list[Path]) -> str:
    parts = []
    for directory in dirs:
        if directory.exists():
            for path in sorted(directory.rglob("*.md")):
                parts.append(path.read_text(encoding="utf-8"))
    return "\n\n".join(parts)


def _recent_user(messages, *, cap: int) -> str:
    users = [
        _content(_message_dict(message))
        for message in messages
        if _message_dict(message).get("role") == "user"
    ]
    return _cap("\n\n".join(users[-8:]), cap)


def _cap(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 16].rstrip() + "\n...[truncated]"


def _extract_section(markdown: str, title: str) -> str:
    marker = f"## {title}"
    if marker not in markdown:
        return ""
    after = markdown.split(marker, 1)[1]
    if "\n## " in after:
        after = after.split("\n## ", 1)[0]
    return after.strip()


def _iter_context_docs(root: Path):
    for path in sorted(root.rglob("*.md")):
        parts = path.relative_to(root).parts
        scope = parts[0] if parts else "unknown"
        yield ContextDoc(path, scope, path.read_text(encoding="utf-8"))


def _fts_query(query: str) -> str:
    tokens = re.findall(r"[\wа-яА-ЯёЁ-]+", query)
    return " OR ".join(f'"{token}"' for token in tokens) or '""'


def _safe_component(value: str) -> str:
    safe = re.sub(r"[^0-9A-Za-z_.-]+", "-", value).strip(".-")
    return safe or "unknown"
